### ISSUE TITLE
Investigate using SpaceNet examples with no AWS account set up

### ISSUE THREAD

**Issue by lossyrob** [azavea/raster-vision-examples#11]
A user ran the spacenet example notebook without having an aws cli configuration on their machine. This cause a `ProfileNotFound: The config profile (default) could not be found` error on the `s3 = boto3.client('s3')` line.

Modify the example notebook and/or docker container setup to allow users without aws cli set up on the host machine to run the notebook.

**Comment by lossyrob** [comment]
Workaround if you have an AWS account: install the [aws-cli](https://docs.aws.amazon.com/cli/latest/userguide/installing.html) and run `aws configure` [to setup the default profile](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html)

**Comment by lewfish** [comment]
I thought you needed an AWS account to access public spacenet data. (Which seems strange). But, if that's true then this won't be possible.

**Comment by jamesmcclain** [comment]
One the page https://spacenetchallenge.github.io/ one can find the following text related to their examples using SpaceNet (emphasis added):

> The AWS Command Line Interface (CLI) must be installed **with an active AWS account**. Configure the AWS CLI using ‘aws configure’

Based on this and other factors, it appears that an account is needed (even if no dollars will ever charged to that account to access the SpaceNet data on AWS).

**Comment by lossyrob** [comment]
Thanks for looking into that.
