### ISSUE TITLE
minimum system required to execute the examples

### ISSUE THREAD

**Issue by geopamplona** [azavea/raster-vision-examples#24]
Hello
I face the examples, but I take a long time to execute them .. around 8 hours ..
what would be a resonable time to execute the object detection xview example?
What should be the minimum system required to execute the examples in a reasonable time?
what gpu? how much ram? etc...
Thank you

**Comment by lewfish** [comment]
There aren't any minimum requirements per se, but I can run small test examples on a 4 year old laptop with 8gb of ram. for really training a model, 8 hours sounds about right on a half-way decent gpu (like a k80 or 1080gtx). on a cpu it will take much longer (20x?). If you have problems running out of GPU RAM, try decreasing the batch size or use a smaller model architecture.

**Comment by geopamplona** [comment]
I am using the cpu docker on a computer with 10gb of ram and intel i5
I do not have a GPU now
how long does it take to execute object detection xview, for both models on your laptop? So I have an estimate of whether my system is incorrectly configured or similar.
Does it influence that you use docker? or alpine linux?
gtx1080 is just the graphic card that I intend to buy soon; Is it a good recommendation for a desktop computer?
Thank you very much for the information

**Comment by lewfish** [comment]
I'd imagine that running the full training on a CPU would take a few weeks -- in other words, it's impractical and you shouldn't do it. I'm not in a position to give recommendations on GPUs but I've heard the 1080 mentioned as a cost-effective option.
