### ISSUE TITLE
About the Spacenet Vegas Roads model

### ISSUE THREAD

**Issue by hoonkai** [azavea/raster-vision-examples#44]
Hi

Can I ask how the Spacenet Vegas Roads model pretrained? Is it pretrained on COCO, VOC 2012 or other datasets? Also, I see that the network backbone is Mobilenet-v2, what's the depth-multiplier? Does the model employ ASPP and decoder modules?

Thanks

**Comment by lewfish** [comment]
Based on the name of the pretrained model file, I think it was trained on VOC 2012 using Deeplab v3 which uses ASPP. I'm not sure about using the decoder modules or the depth multiplier, but here is some information which might help you figure this out:

* It was trained using this script https://github.com/azavea/raster-vision-examples/blob/master/spacenet/vegas.py (not sure which version though -- we should track that) 
* This is where we configure the backend. https://github.com/azavea/raster-vision-examples/blob/master/spacenet/vegas.py#L227-L233
* In particular the `with_model_defaults` line grabs all the model defaults for that model type which is Mobilenet V2. 
* This data comes from https://github.com/azavea/raster-vision/blob/develop/rastervision/backend/model_defaults.json#L111-L130 
* We take that configuration object and use it to construct the args passed to the training script here https://github.com/azavea/raster-vision/blob/develop/rastervision/backend/tf_deeplab.py#L332-L405 * This is where we install Deeplab https://github.com/azavea/raster-vision/blob/develop/Dockerfile#L30-L33

**Comment by yoninachmany** [comment]
`Note MobileNet-v2 based models do not employ ASPP and decoder modules for fast computation.` https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/model_zoo.md
