### ISSUE TITLE
predict not showing any output/error

### ISSUE THREAD

**Issue by ammar-mahmood** [azavea/raster-vision-examples#58]
Hi,

I installed rv 0.9 using pip install and everything is in order. However, when I run the predict command on the Potsdam predict package from the model zoo with an image from the same dataset, it runs  (takes 2-3 seconds) but shows no error or any output in the desired directory. 

The command is run from the same folder the files are located in: 

 rastervision predict ./predict_package.zip ./sample.tif  ./predictions.tif

What can be the issue?

**Comment by lewfish** [comment]
Are you sure you are on 0.9? You can use `pip show rastervision` to see the version. Were you able to run the Quickstart example? Also, it's pretty easy to mess up installing via pip since there are a lot of external dependencies that are needed, so I'd recommend using the Docker setup https://docs.rastervision.io/en/0.9/setup.html#docker-containers

**Comment by lewfish** [comment]
I ran this inside the Docker container and it worked. I will have to test if it works when installing via `pip` later.

```
root@2a97fefc318f:/opt/data/model-zoo/potsdam-seg# ls
3_12_sample.tif  3_12_sample.tif.aux.xml  model.tar.gz  predict_package.zip
root@2a97fefc318f:/opt/data/model-zoo/potsdam-seg# rastervision predict ./predict_package.zip ./3_12_sample.tif ./out.tif
/usr/local/lib/python3.5/dist-packages/pluginbase.py:439: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  fromlist, level)
2019-04-17 21:34:32.924251: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-04-17 21:34:32:rastervision.task.semantic_segmentation: INFO - Making predictions for scene
......................................................................................................................................................................................root@2a97fefc318f:/opt/data/model-zoo/potsdam-seg# ls
3_12_sample.tif  3_12_sample.tif.aux.xml  model.tar.gz  out.tif  predict_package.zip
```

**Comment by ammar-mahmood** [comment]
I am on 0.9.0rc1

I was able to run the dry test on the Potsdam segmentation example. However, I got the ''“FileNotFoundError: [WinError 2] The system cannot find the file specified” error when I ran the full experiment. 

It seems like I need to run it from the docker. 

Thank you.
